### ISSUE TITLE
Component List

### ISSUE THREAD

**Issue by diegotheslinger** [bdring/TWANG32#13]
Hello, was wondering if anyone knew where to find a component list for this project?  Saw the kit is unavailable from tindie.  I already have the board printed out, just wondering on component sizes as im not super familiar with surface mount packages. 

Thank You.

**Comment by bdring** [comment]
I can do that in a few days.

**Comment by diegotheslinger** [comment]
Wow thank you that would be helpful!

**Comment by bdring** [comment]
[Here is what I have](https://github.com/bdring/TWANG32/blob/master/parts/diptrace/twang32_pcb_bom.csv)
