### ISSUE TITLE
Conveyor belt not working and lava not working properly..

### ISSUE THREAD

**Issue by yuppicide** [bdring/TWANG32#6]
So I received my Twang32 prebuilt from you except for the LED wire. We tested it out using two APA102's. I adjusted brightness, sound volume, attack sensitivity, and 288 LED's. It was working fine. My friends had a blast with it!

I took it home and played a game or two and it was working fine. However, later that night I came back and the conveyor belt did not light up (invisible/lights off) but it still functions properly (pushes you backwards). The lava doesn't look like it used to. Instead of twinkling when it's safe to cross, it does not light up (invisible/lights off) but still functions properly (kills me).

Any ideas what is wrong here?

(Also, side note.. how come my lives (and your video on YouTube) show the lives on the bottom next to the controller, but this guy https://www.youtube.com/watch?v=pCQsKuKeDGg his is at the top of the LED strip)

**Comment by yuppicide** [comment]
PS - I  have already tried recompiling and I have 2 more LED strips I tested. Same issue.. no conveyor or lava.

**Comment by bdring** [comment]
Try increasing the brightness to full, just as a test.

**Comment by yuppicide** [comment]
Already figured it out. I wish I would have figured it out before posting a
bug. 35 brightness shows.. I'm not sure the exact number but 25 definitely
doesn't show.

I was playing in the house and didn't wanna bother anyone is why I had it
down.

**Comment by bdring** [comment]
I have seen that on WS2812 strips, but not on APA102 strips, so i guessed that might be it. The brightness is a global thing and some of the lighter items drop out first.

In [config.h](https://github.com/bdring/TWANG32/blob/master/TWANG32/config.h#L50) you will see some compensation values for the strip types. These were chosen for the strips I tested. You could tweak those values if need be.

**Comment by bdring** [comment]
Also, you will probably never be able to use the full, low end, range of the brightness on all strip types. Something will drop out first.
