### ISSUE TITLE
Accelerometer data freezes

### ISSUE THREAD

**Issue by afreeland** [bdring/TWANG32#7]
I have been seeing an issue where, what appears to be randomly, the accelerometer data just stops working with the game. The green LED player will just stop moving...all other neopixel leds still work (enemies move, lava flows, death animation works, random led sequence post game). Once the game stops accepting accelerometer input, nothing seems to fix it but a hard power reboot.  I have triple checked the cabling to ensure no shorts...tried various accelerometer chips but with no luck.   

I seen another [issue on interrupts](https://github.com/bdring/TWANG32/issues/1#issuecomment-545228889) and was sure if that was related or not.  Just looking for any guidance on how to test or if you have seen this issue.  

Hardware:
- DOIT Esp32 DevKit v1 board
- [WS2812B](https://www.amazon.com/gp/product/B01LSF4Q0A/ref=ppx_yo_dt_b_asin_title_o04_s01?ie=UTF8&psc=1) NeoPixels
- [MPU6050](https://www.amazon.com/gp/product/B00LP25V1A/ref=ppx_yo_dt_b_asin_title_o03_s00?ie=UTF8&psc=1)

I did see the debug lines for serial and will try that...I mounted LEDs to a wall already and it makes the reading of serial a little trickier now.  I probably should of worked out the kinks before going all in lol :)
https://github.com/bdring/TWANG32/blob/0ef73584328d7b5b7d4b6bc1e1dc2b60e992db4c/TWANG32/TWANG32.ino#L1145-L1148

**Comment by bdring** [comment]
I have seen lock ups, but quite rarely. I can have it running for hours without issue. 

I wonder if you go a few loops without proper data, the gyro could be re-initialized 

```C++
accelgyro.initialize();
```

I have not played with the code in a while, but recently thought of some new level ideas. I thought some lava options could be tried. If it flowed or grew, it could create some urgency to complete levels.  I might give another look at the accel code then.

**Comment by afreeland** [comment]
Thanks for the response and will look into the `initialize()` code.  I wish I wasn't so garbage at c/c++ or I could help...if this was like C#, JS, Go, Python...anything else lol.  I am just so terribly slow with c++.

The Lava _flowing_ sounds like a really cool improvement and forcing urgency would be a great addition.  

You ever noticed any feedback to audio from wifi?  I am using [Adafruit Mono 2.5w amp](https://www.adafruit.com/product/2130) and have noticed that I get this constant ticking audio.  I see the blips in the oscilliscope and I cant seem to track down what is causing it...I put my finger over the wireless antenna and noticed that the _ticking_ was greatly reduced (barely audible).  They are side by side on the board and thought that may be causing me some issues.

**Comment by bdring** [comment]
I have not heard any ticking sounds. Try switching DAC outputs. How wide is the tick on the scope? Could you filter it? I use the [PAM8403](https://www.aliexpress.com/item/1822706737.html)

I think an early level with lava moving down would be a good introduction. Lava growing from the bottom would be a great way to push you along. Lava growing in the middle would eventually be to wide to cross and force death near the bottom.

**Comment by afreeland** [comment]
> I have not heard any ticking sounds. Try switching DAC outputs. How wide is the tick on the scope? Could you filter it? I use the [PAM8403](https://www.aliexpress.com/item/1822706737.html)
> 
> I think an early level with lava moving down would be a good introduction. Lava growing from the bottom would be a great way to push you along. Lava growing in the middle would eventually be to wide to cross and force death near the bottom.

So was just doing some serial monitor debugging and trying to identify the issues with the accelerometer.  I got distracted by the ticking sound and swapped out DAC pin 25 for 26 and was still hearing it.  I was really suspicious of the wifi module since when I press on the antenna the ticking almost disappears.  

Commented out this line just to try: https://github.com/bdring/TWANG32/blob/master/TWANG32/TWANG32.ino#L226

Sure enough the ticking is now gone but so would my webserver.  I may throw a different esp32 at it and see if that helps and when I build the stand for the twang stick I may put some distance between the audio amp/speaker and the board.  Just figured I would give an update on that very strange issue.  Not sure if its an interference issue or something with how the wifi lib operates...but I am guessing interference since you have not seen that issue.

**Comment by bdring** [comment]
Thanks for the update. Nice job isolating it to the wifi.

I will probably start looking at the accel and lava code on Monday.

**Comment by bdring** [comment]
If you turn of the serial debugging and have a screen lockup. Tell me what the values are.

**Comment by bdring** [comment]
I got some time and added the flowing and growing lava. It really adds a sense of panic to some levels. I added a few new levels with various implementations.  I'll push the changes tomorrow.

**BTW:** I had it running for about 2 hours while writing and testing with no lockups.
